.TH zmq 7 "" "(c)2007-2009 FastMQ Inc." "0MQ User Manuals"
.SH NAME
0MQ \- lightweight messaging kernel
.SH DESCRIPTION
0MQ is an extensible messaging framework. It allows you to send messages though
the network at hight data rates and low latencies. 
.SH MULTI-PROTOCOL SUPPORT
0MQ allows for different transport-level and MOM-level protocols.
Following section describes how to specify where the entities are
located on the network (see
.IR api_thread_t::create_exchange
and
.IR api_thread_t::create_queue
methods).
.IP "\fB0MQ backend protocol over TCP/IP\fP"
.RS
.TP 10
.I Format:
bp/tcp://network-interface:port
.TP 
Examples: bp/tcp://eth0:5555 or bp/tcp://192.168.1.1:5555
.RE
.IP "\fBSCTP protocol\fP"
.RS
.TP 10
.I Format:
sctp://network-interface:port
.TP 
Examples: sctp://eth0:5555 or sctp://192.168.1.2:5555
.RE
.IP "\fBAMQP protocol\fP"
.RS
.TP 10
.I Format:
amqp://broker-host:port
.TP 
Example:  amqp://192.168.1.3:5672 or amqp://server001:5672
.RE
.IP "\fB0MQ backend protocol over PGM\fP"
.RS
.TP 10
.I Format:
bp/pgm://network-interface;multicast-group:port
.BR
bp/pgm://udp:network-interface;multicast-group:port
.TP
The latter version causes PGM packets to be encapsulated in UDP packets.
.TP
Example:  bp/pgm://eth0;226.0.0.1:7501
.RE
.SH WEB PAGE
Documentation related to 0MQ project can be found on \fBwww.zeromq.org\fP.
.SH MAILING LIST
Mailing list for 0MQ project is \fB<zeromq-dev@lists.zeromq.org>\fP
.SH AUTHOR
Pavol Malosek <malosek at fastmq dot com>
.SH "SEE ALSO"
.BR zmq_server (1),
.BR zmq::locator_t (3),
.BR zmq::api_thread_t (3),
.BR zmq::io_thread_t (3),
.BR zmq::dispatcher_t (3),
.BR zmq::message_t (3),
.BR zmq::select_thread_t (3),
.BR zmq::poll_thread_t (3),
.BR zmq::epoll_thread_t (3),
.BR zmq::devpoll_thread_t (3),
.BR zmq::kqueue_thread_t (3),
.BR zmq::set_error_handler (3)

